{
 "title": "Green Streaming Analytics - Per-session view",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sessionID",
    "label": "Session",
    "query": "select distinct \"Sessions\".\"id\" from \"Sessions\";"
   },
   { "name": "cmcd_metric", "label": "CMCD Metric", "query": "br,bl,bs,d,dl,mtp,pr,rtp,su,tb" }
  ]
 },
 "panels": [
  {
   "title": "Session metadata",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH numberOfCmcdEntriesBySid as (\n  select\n    count(id) as \"cmcdEntries\",\n    max(\"createdAt\") as \"latestCmcdEntry\",\n    \"sid\"\n    FROM \"Cmcds\"\n    group by \"sid\"\n),\ncombined as (\n  SELECT\n    \"id\" as \"ID\",\n    \"deviceSerialNumber\" as \"NETIO Serial Number\",\n    \"deviceIP\" as \"NETIO Device IP\",\n    case\n      when \"terminatedOn\" is null then EXTRACT(EPOCH FROM (NOW() - \"createdAt\"))\n      else null\n    end as \"Active since (seconds)\",\n    case\n      when \"terminatedOn\" is not null then EXTRACT(EPOCH FROM (NOW() - \"terminatedOn\"))\n      else null\n    end as \"Inactive since (seconds)\",\n    \"createdAt\" as \"Created at\",\n    \"terminatedOn\" as \"Terminated on\",\n    \"cmcdEntries\" as \"Number of CMCD entries\",\n    \"latestCmcdEntry\" as \"Latest CMCD entry\"\n  FROM \"Sessions\" LEFT JOIN numberOfCmcdEntriesBySid ON \"Sessions\".\"id\" = numberOfCmcdEntriesBySid.\"sid\"\n  WHERE \"Sessions\".\"id\" = '$sessionID'\n  ORDER BY \"createdAt\" DESC\n)\nselect * from combined"
    }
   ]
  },
  { "title": "Detailed energy consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Average consumption (W)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(total_load) FROM \"Netios\" WHERE session_id = '$sessionID' "
    }
   ]
  },
  {
   "title": "Power consumption (W)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT \"createdAt\", total_load, session_id\nFROM \"Netios\"\nWHERE session_id = '$sessionID'\nAND \"createdAt\" between '${__from:date}' and '${__to:date}'"
    },
    {
     "rawSql": "WITH FIRST_CMCD_ENTRY AS (\n  SELECT \n    MIN(\"createdAt\") AS MAX_DATE\n  FROM \"Cmcds\"\n  WHERE sid = '$sessionID'\n),\nAVERAGE_LOAD AS (\n  SELECT \n    CASE\n      WHEN AVG(total_load) IS NULL THEN 100\n      ELSE AVG(total_load)\n    END AS load\n  FROM \"Netios\"\n  WHERE session_id = '$sessionID'\n  AND \"createdAt\" < (SELECT MAX_DATE FROM FIRST_CMCD_ENTRY)\n)\nSELECT AVERAGE_LOAD.load AS baseload,\n\"Netios\".\"createdAt\"\nFROM \"Netios\"\nJOIN AVERAGE_LOAD ON 1=1"
    },
    {
     "rawSql": "WITH ENERGY_CONSUMPTION AS (\n  SELECT \"createdAt\", total_load, session_id\n  FROM \"Netios\"\n  WHERE session_id = '$sessionID'\n  AND \"createdAt\" between '${__from:date}' and '${__to:date}'\n),\nFIRST_CMCD_ENTRY AS (\n    SELECT \n      MIN(\"createdAt\") AS MAX_DATE\n    FROM \"Cmcds\"\n    WHERE sid = '$sessionID'\n),\nAVERAGE_LOAD AS (\n  SELECT \n    CASE\n      WHEN AVG(total_load) IS NULL THEN 100\n      ELSE AVG(total_load)\n    END AS load\n  FROM \"Netios\"\n  WHERE session_id = '$sessionID'\n  AND \"createdAt\" < (SELECT MAX_DATE FROM FIRST_CMCD_ENTRY)\n)\nSELECT\n  \"createdAt\",\n  total_load - (SELECT load FROM AVERAGE_LOAD) as load_minus_baseload\nFROM ENERGY_CONSUMPTION"
    }
   ]
  },
  {
   "title": "Baseline consumption (W)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH FIRST_CMCD_ENTRY AS (\n  SELECT \n    MIN(\"createdAt\") AS MAX_DATE\n  FROM \"Cmcds\"\n  WHERE sid = '$sessionID'\n),\nAVERAGE_LOAD AS (\n  SELECT \n    CASE\n      WHEN AVG(total_load) IS NULL THEN 100\n      ELSE AVG(total_load)\n    END AS load\n  FROM \"Netios\"\n  WHERE session_id = '$sessionID'\n  AND \"createdAt\" < (SELECT MAX_DATE FROM FIRST_CMCD_ENTRY)\n)\nSELECT AVERAGE_LOAD.load AS baseload\nFROM AVERAGE_LOAD"
    }
   ]
  },
  {
   "title": "Average consumption (W) during playback",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH FIRST_CMCD_ENTRY AS (\n  SELECT \n    MIN(\"createdAt\") AS MAX_DATE\n  FROM \"Cmcds\"\n  WHERE sid = '$sessionID'\n)\nSELECT AVG(total_load) FROM \"Netios\" WHERE session_id = '$sessionID' AND \"createdAt\" > (SELECT MAX_DATE FROM FIRST_CMCD_ENTRY)"
    }
   ]
  },
  {
   "title": "Key CMCD metrics and energy consumption",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }
  },
  {
   "title": "Measured throughput (kbps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT sid, \"createdAt\", mtp as \"Measured throughput\" FROM \"Cmcds\" WHERE (type = 'video' AND sid = '${sessionID}' AND \"createdAt\" between '${__from:date}' and '${__to:date}') "
    },
    {
     "rawSql": "SELECT \"createdAt\", total_load, session_id FROM \"Netios\" WHERE session_id = '$sessionID' AND \"createdAt\" between '${__from:date}' and '${__to:date}'"
    },
    {
     "rawSql": "WITH FIRST_CMCD_ENTRY AS (\n  SELECT \n    MIN(\"createdAt\") AS MAX_DATE\n  FROM \"Cmcds\"\n  WHERE sid = '$sessionID'\n),\nAVERAGE_LOAD AS (\n  SELECT \n    CASE\n      WHEN AVG(total_load) IS NULL THEN 100\n      ELSE AVG(total_load)\n    END AS load\n  FROM \"Netios\"\n  WHERE session_id = '$sessionID'\n  AND \"createdAt\" < (SELECT MAX_DATE FROM FIRST_CMCD_ENTRY)\n)\nSELECT AVERAGE_LOAD.load AS baseload,\n\"Netios\".\"createdAt\"\nFROM \"Netios\"\nJOIN AVERAGE_LOAD ON 1=1"
    },
    {
     "rawSql": "WITH ENERGY_CONSUMPTION AS (\n  SELECT \"createdAt\", total_load, session_id FROM \"Netios\" WHERE session_id = '$sessionID' AND \"createdAt\" between '${__from:date}' and '${__to:date}'\n),\nFIRST_CMCD_ENTRY AS (\n    SELECT \n      MIN(\"createdAt\") AS MAX_DATE\n    FROM \"Cmcds\"\n    WHERE sid = '$sessionID'\n),\nAVERAGE_LOAD AS (\n  SELECT \n    CASE\n      WHEN AVG(total_load) IS NULL THEN 100\n      ELSE AVG(total_load)\n    END AS load\n  FROM \"Netios\"\n  WHERE session_id = '$sessionID'\n  AND \"createdAt\" < (SELECT MAX_DATE FROM FIRST_CMCD_ENTRY)\n)\nSELECT\n  \"createdAt\",\n  total_load - (SELECT load FROM AVERAGE_LOAD) as load_minus_baseload\nFROM ENERGY_CONSUMPTION"
    }
   ]
  },
  {
   "title": "Bitrate (kbps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT sid, \"createdAt\", br as \"Bitrate\" FROM \"Cmcds\" WHERE (type = 'video' AND sid = '${sessionID}' AND \"createdAt\" between '${__from:date}' and '${__to:date}') "
    },
    {
     "rawSql": "SELECT \"createdAt\", total_load, session_id FROM \"Netios\" WHERE session_id = '$sessionID' AND \"createdAt\" between '${__from:date}' and '${__to:date}'"
    },
    {
     "rawSql": "WITH FIRST_CMCD_ENTRY AS (\n  SELECT \n    MIN(\"createdAt\") AS MAX_DATE\n  FROM \"Cmcds\"\n  WHERE sid = '$sessionID'\n),\nAVERAGE_LOAD AS (\n  SELECT \n    CASE\n      WHEN AVG(total_load) IS NULL THEN 100\n      ELSE AVG(total_load)\n    END AS load\n  FROM \"Netios\"\n  WHERE session_id = '$sessionID'\n  AND \"createdAt\" < (SELECT MAX_DATE FROM FIRST_CMCD_ENTRY)\n)\nSELECT AVERAGE_LOAD.load AS baseload,\n\"Netios\".\"createdAt\"\nFROM \"Netios\"\nJOIN AVERAGE_LOAD ON 1=1"
    },
    {
     "rawSql": "WITH ENERGY_CONSUMPTION AS (\n  SELECT \"createdAt\", total_load, session_id FROM \"Netios\" WHERE session_id = '$sessionID' AND \"createdAt\" between '${__from:date}' and '${__to:date}'\n),\nFIRST_CMCD_ENTRY AS (\n    SELECT \n      MIN(\"createdAt\") AS MAX_DATE\n    FROM \"Cmcds\"\n    WHERE sid = '$sessionID'\n),\nAVERAGE_LOAD AS (\n  SELECT \n    CASE\n      WHEN AVG(total_load) IS NULL THEN 100\n      ELSE AVG(total_load)\n    END AS load\n  FROM \"Netios\"\n  WHERE session_id = '$sessionID'\n  AND \"createdAt\" < (SELECT MAX_DATE FROM FIRST_CMCD_ENTRY)\n)\nSELECT\n  \"createdAt\",\n  total_load - (SELECT load FROM AVERAGE_LOAD) as load_minus_baseload\nFROM ENERGY_CONSUMPTION"
    }
   ]
  },
  {
   "title": "Buffer length (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT sid, \"createdAt\", bl as \"Buffer length\" FROM \"Cmcds\" WHERE (type = 'video' AND sid = '${sessionID}' AND \"createdAt\" between '${__from:date}' and '${__to:date}')"
    },
    {
     "rawSql": "SELECT \"createdAt\", total_load, session_id FROM \"Netios\" WHERE session_id = '$sessionID' AND \"createdAt\" between '${__from:date}' and '${__to:date}'"
    },
    {
     "rawSql": "WITH FIRST_CMCD_ENTRY AS (\n  SELECT \n    MIN(\"createdAt\") AS MAX_DATE\n  FROM \"Cmcds\"\n  WHERE sid = '$sessionID'\n),\nAVERAGE_LOAD AS (\n  SELECT \n    CASE\n      WHEN AVG(total_load) IS NULL THEN 100\n      ELSE AVG(total_load)\n    END AS load\n  FROM \"Netios\"\n  WHERE session_id = '$sessionID'\n  AND \"createdAt\" < (SELECT MAX_DATE FROM FIRST_CMCD_ENTRY)\n)\nSELECT AVERAGE_LOAD.load AS baseload,\n\"Netios\".\"createdAt\"\nFROM \"Netios\"\nJOIN AVERAGE_LOAD ON 1=1"
    },
    {
     "rawSql": "WITH ENERGY_CONSUMPTION AS (\n  SELECT \"createdAt\", total_load, session_id FROM \"Netios\" WHERE session_id = '$sessionID' AND \"createdAt\" between '${__from:date}' and '${__to:date}'\n),\nFIRST_CMCD_ENTRY AS (\n    SELECT \n      MIN(\"createdAt\") AS MAX_DATE\n    FROM \"Cmcds\"\n    WHERE sid = '$sessionID'\n),\nAVERAGE_LOAD AS (\n  SELECT \n    CASE\n      WHEN AVG(total_load) IS NULL THEN 100\n      ELSE AVG(total_load)\n    END AS load\n  FROM \"Netios\"\n  WHERE session_id = '$sessionID'\n  AND \"createdAt\" < (SELECT MAX_DATE FROM FIRST_CMCD_ENTRY)\n)\nSELECT\n  \"createdAt\",\n  total_load - (SELECT load FROM AVERAGE_LOAD) as load_minus_baseload\nFROM ENERGY_CONSUMPTION"
    }
   ]
  },
  {
   "title": "Selectable CMCD metric and energy consumption",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }
  },
  {
   "title": "${cmcd_metric} against power consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT sid, \"createdAt\", ${cmcd_metric} FROM \"Cmcds\" WHERE (type = 'video' AND sid = '${sessionID}' AND \"createdAt\" between '${__from:date}' and '${__to:date}') "
    },
    {
     "rawSql": "SELECT \"createdAt\", total_load, session_id FROM \"Netios\" WHERE session_id = '$sessionID' AND \"createdAt\" between '${__from:date}' and '${__to:date}'"
    },
    {
     "rawSql": "WITH FIRST_CMCD_ENTRY AS (\n  SELECT \n    MIN(\"createdAt\") AS MAX_DATE\n  FROM \"Cmcds\"\n  WHERE sid = '$sessionID'\n),\nAVERAGE_LOAD AS (\n  SELECT \n    CASE\n      WHEN AVG(total_load) IS NULL THEN 100\n      ELSE AVG(total_load)\n    END AS load\n  FROM \"Netios\"\n  WHERE session_id = '$sessionID'\n  AND \"createdAt\" < (SELECT MAX_DATE FROM FIRST_CMCD_ENTRY)\n)\nSELECT AVERAGE_LOAD.load AS baseload,\n\"Netios\".\"createdAt\"\nFROM \"Netios\"\nJOIN AVERAGE_LOAD ON 1=1"
    },
    {
     "rawSql": "WITH ENERGY_CONSUMPTION AS (\n  SELECT \"createdAt\", total_load, session_id FROM \"Netios\" WHERE session_id = '$sessionID' AND \"createdAt\" between '${__from:date}' and '${__to:date}'\n),\nFIRST_CMCD_ENTRY AS (\n    SELECT \n      MIN(\"createdAt\") AS MAX_DATE\n    FROM \"Cmcds\"\n    WHERE sid = '$sessionID'\n),\nAVERAGE_LOAD AS (\n  SELECT \n    CASE\n      WHEN AVG(total_load) IS NULL THEN 100\n      ELSE AVG(total_load)\n    END AS load\n  FROM \"Netios\"\n  WHERE session_id = '$sessionID'\n  AND \"createdAt\" < (SELECT MAX_DATE FROM FIRST_CMCD_ENTRY)\n)\nSELECT\n  \"createdAt\",\n  total_load - (SELECT load FROM AVERAGE_LOAD) as load_minus_baseload\nFROM ENERGY_CONSUMPTION"
    }
   ]
  }
 ]
}