name: awt-energy-analytics-${TARGET:-prod}
networks:
    default:

services:
    media-player:
        container_name: media-player
        build:
            context: ./media-player
            dockerfile: Dockerfile
        environment:
            VITE_MEASUREMENT_SERVER: ${VITE_MEASUREMENT_SERVER}
        ports:
            - "5173:5173"
        command: npm run dev
        networks:
            default:
    measurement-db:
        networks:
            default:
        container_name: measurement-db
        environment:
            POSTGRES_DB: "${MEASUREMENT_POSTGRES_DB}"
            POSTGRES_USER: "${MEASUREMENT_POSTGRES_USER}"
            POSTGRES_PASSWORD: "${MEASUREMENT_POSTGRES_PASSWORD}"
        image: "postgres:14"
        volumes:
            - ${MEASUREMENT_DB_VOLUME}:/var/lib/postgresql/data/
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U measurement"]
            interval: 1s
            timeout: 5s
            retries: 10
    measurement-service:
        container_name: measurement-service
        build:
            context: ./measurement-service
            dockerfile: Dockerfile
        entrypoint: "node index.js"
        environment:
            MEASUREMENT_POSTGRES_DB: ${MEASUREMENT_POSTGRES_DB}
            MEASUREMENT_POSTGRES_USER: ${MEASUREMENT_POSTGRES_USER}
            MEASUREMENT_POSTGRES_HOST: ${MEASUREMENT_POSTGRES_HOST}
            MEASUREMENT_POSTGRES_PASSWORD: ${MEASUREMENT_POSTGRES_PASSWORD}
            MEASUREMENT_POSTGRES_PORT: ${MEASUREMENT_POSTGRES_PORT}
            SERVICE_PORT: ${SERVICE_PORT:-8080}
            TARGET: ${TARGET:-prod}
        # volumes:
        #  - ./measurement-service/:/usr/app
        expose:
          - ${SERVICE_PORT:-8080}
        depends_on:
            measurement-db:
                condition: service_healthy
        ports:
            - 8080:${SERVICE_PORT:-8080}
        command: npm run dev
        networks:
            default:
    grafana:
        image: grafana/grafana-enterprise
        container_name: grafana
        restart: unless-stopped
        ports:
            - 3000:3000
        volumes:
            - ${GRAFANA_VOLUME}:/var/lib/grafana
volumes:
  grafana-storage: {}
